# Generated by Django 4.2.6 on 2023-11-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='anios',
            new_name='anio',
        ),
        migrations.AddField(
            model_name='paleta',
            name='mod',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
