# Generated by Django 4.2.6 on 2023-11-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_mod_paleta_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('deporte', models.CharField(max_length=15)),
                ('tipo_piso', models.CharField(max_length=15)),
                ('cantidad_horas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelotitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('deporte', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='paleta',
            name='marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paleta',
            name='modelo',
            field=models.CharField(max_length=10),
        ),
    ]
